replicas: 1
minimumMasterNodes: 1
resources:
  requests:
    cpu: "400m"
    memory: "1Gi"
  limits:
    cpu: "400m"
    memory: "1Gi"
volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi