apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roleloeks5092EBB2-3cf336f85da34a0dafb88c1e62eb4ba2
  region: eu-west-1

vpc:
  id: vpc-0f6ae6dd655d21217
  securityGroup: sg-05b363f0b42ec7616
  subnets:
    private:
      eu-west-1a:
          id: subnet-07e63f02be72e7097
      eu-west-1b:
          id: subnet-0f2ecd9d3278eddfa
      eu-west-1c:
          id: subnet-0fa98db8b78ce7f2b
    public:
      eu-west-1a:
          id: subnet-05b56a9efc49dd152
      eu-west-1b:
          id: subnet-0a57e2cc8c50ebe66
      eu-west-1c:
          id: subnet-02dd914a77b97695a

managedNodeGroups:
  - name: ng-1
    instanceType: t2.medium
    desiredCapacity: 1
    volumeSize: 20
    privateNetworking: true