apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roleloeks5092EBB2-fde40caa59a84ecea407a4ba303a4929
  region: eu-west-1

vpc:
  id: vpc-035f0d90862511016
  securityGroup: sg-05b363f0b42ec7616
  subnets:
    private:
      eu-west-1a:
          id: subnet-05fb51436254235da
      eu-west-1b:
          id: subnet-02959577744bcd1b0    
    public:
      eu-west-1a:
          id: subnet-01ea4479c37bbb2c3
      eu-west-1b:
          id: subnet-09743faf1ceef5fd1
          
managedNodeGroups:
  - name: ng-1
    instanceType: t2.medium
    minSize: 1
    maxSize: 2
    desiredCapacity: 1
    volumeSize: 20
    privateNetworking: true