version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - yarn global add lerna
      - yarn global add @babel/cli
      - yarn
      - yarn lerna bootstrap --include-dependencies
  build:
    commands:
      - echo Build started on `date`
      - REACT_APP_ENV=${APP_ENVIRONMENT} yarn lerna run build --scope=${WORKSPACE}
  post_build:
    commands:
      # copy the contents of /build to S3 
      - aws s3 cp --recursive --acl public-read ./packages/${WORKSPACE}/build s3://${DEPLOY_BUCKET}/${WORKSPACE}
      - aws s3 cp --recursive --acl public-read ./packages/${WORKSPACE}/build s3://${DEPLOY_BUCKET}/
      - aws cloudfront create-invalidation --distribution-id ${DISTRIBUTION} --paths /
artifacts:
  files:
    - '**/*'
  base-directory: build