version: 0.2
phases:
  install:
    runtime-version:
      nodejs: 16
  pre_build:
    commands:
     - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 619680812856.dkr.ecr.eu-west-1.amazonaws.com
     - docker build -t dev-registry-clientbackendf728ad9b-kkvu07aaz58s ./packages/backend
     - docker tag dev-registry-clientbackendf728ad9b-kkvu07aaz58s:latest 619680812856.dkr.ecr.eu-west-1.amazonaws.com/dev-registry-clientbackendf728ad9b-kkvu07aaz58s:latest
     - docker push 619680812856.dkr.ecr.eu-west-1.amazonaws.com/dev-registry-clientbackendf728ad9b-kkvu07aaz58s:latest
artifacts:
  files:
    - '**/*'
  base-directory: build