version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - REACT_APP_ENV=${APP_ENVIRONMENT} yarn workspace ${WORKSPACE} build
  post_build:
    commands:
      # copy the contents of /build to S3 
      - aws s3 cp --recursive --acl public-read ./build s3://${DEPLOY_BUCKET}/ 
      - aws cloudfront create-invalidation --distribution-id ${DISTRIBUTION} --paths /
artifacts:
  files:
    - '**/*'
  base-directory: build