version: '3.7'
services:
  mongodb_container:
    image: mongo:6.0.1
    environment:
      MONGO_INITDB_ROOT_USERNAME: amir
      MONGO_INITDB_ROOT_PASSWORD: shojae
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  # server:
  #   build: .
  #   ports:
  #     - "8080:8080"
  #     - "9229:9229"
  #   depends_on:
  #     - mongodb_container
  #   links:ww
  #     - mongodb_container:mongodb_container
  #   volumes:
  #     - .:/app
  #   command: npm run dev
volumes:
  mongodb_data_container: